### ISSUE TITLE
Not able to clone wip nor colored

### ISSUE THREAD

**Issue by off-bank** [Colored-Coins/Colored-coins-add-on-for-Copay#15]
Cloning from troggy wip branch or colored to ubuntu as instructed gives me the following same error:

bower ECMDERR       Failed to execute "git checkout 4757cfd309665902e67a2b2cd3d78bd91b224ae3", exit code of #128 fatal: reference is not a tree: 4757cfd309665902e67a2b2cd3d78bd91b224ae3

**Comment by off-bank** [comment]
That reference comes from bower.json:

```
"angular-bitcore-wallet-client": "troggy/angular-bitcore-wallet-client#4757cfd309665902e67a2b2cd3d78bd91b224ae3",
```

**Comment by troggy** [comment]
I've updated "colored" branch and instructions. Please try again (note that addon name changed) Things got simpler now — no need to setup BWS

**Comment by off-bank** [comment]
Quick install works like a charm now. Thanks!
