### ISSUE TITLE
Build Failing

### ISSUE THREAD

**Issue by pooleja** [Colored-Coins/Colored-coins-add-on-for-Copay#18]
Was just playing with this and looks like the troggy repo is not available?

bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://github.com/troggy/angular-bitcore-wallet-client.git", exit code of #128 fatal: remote error:    Repository not found.

**Comment by troggy** [comment]
@pooleja This "addon" was made for old Copay 1.8 and is outdated now.
For the integration with latest Copay 2.7.0 please see https://github.com/Colored-Coins/colored-coins-copay-wallet

**Comment by pooleja** [comment]
Awesome. Thanks!

**Comment by troggy** [comment]
@pooleja Fogot to mention that there are two colored Copay app versions:
1. The one based on current production version of Copay 2.7.0. It is now on [master](https://github.com/Colored-Coins/colored-coins-copay-wallet/tree/master) branch and running live at http://copay.coloredcoins.org/.
2. Based on bitpay/copay master branch (unreleased). It is on [dev](https://github.com/Colored-Coins/colored-coins-copay-wallet/dev) branch

When I've [sent](https://github.com/Colored-Coins/Colored-coins-add-on-for-Copay/issues/18#issuecomment-250905180) you the link before, the repository had "dev" version in the master branch, not the Copay 2.7.0. That was my mistake, sorry for that. If you are using it now, you might be using the different version.
